version: "3.4"

services:
     
    react:
        build:
          context: "../05-hooks-app"
        image: reactdocker
        env_file:
          - "../05-hooks-app/.env"
        ports:
          - 5000:3000